// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: holiday/v1/service.proto
//

import Connect
import Foundation
import SwiftProtobuf

public protocol Holiday_V1_HolidaysServiceClientInterface: Sendable {

    @discardableResult
    func `getHolidaysInRange`(request: Holiday_V1_GetHolidaysInRangeRequest, headers: Connect.Headers, completion: @escaping @Sendable (ResponseMessage<Holiday_V1_GetHolidaysInRangeResponse>) -> Void) -> Connect.Cancelable

    @available(iOS 13, *)
    func `getHolidaysInRange`(request: Holiday_V1_GetHolidaysInRangeRequest, headers: Connect.Headers) async -> ResponseMessage<Holiday_V1_GetHolidaysInRangeResponse>
}

/// Concrete implementation of `Holiday_V1_HolidaysServiceClientInterface`.
public final class Holiday_V1_HolidaysServiceClient: Holiday_V1_HolidaysServiceClientInterface, Sendable {
    private let client: Connect.ProtocolClientInterface

    public init(client: Connect.ProtocolClientInterface) {
        self.client = client
    }

    @discardableResult
    public func `getHolidaysInRange`(request: Holiday_V1_GetHolidaysInRangeRequest, headers: Connect.Headers = [:], completion: @escaping @Sendable (ResponseMessage<Holiday_V1_GetHolidaysInRangeResponse>) -> Void) -> Connect.Cancelable {
        return self.client.unary(path: "/holiday.v1.HolidaysService/GetHolidaysInRange", idempotencyLevel: .unknown, request: request, headers: headers, completion: completion)
    }

    @available(iOS 13, *)
    public func `getHolidaysInRange`(request: Holiday_V1_GetHolidaysInRangeRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Holiday_V1_GetHolidaysInRangeResponse> {
        return await self.client.unary(path: "/holiday.v1.HolidaysService/GetHolidaysInRange", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    public enum Metadata {
        public enum Methods {
            public static let getHolidaysInRange = Connect.MethodSpec(name: "GetHolidaysInRange", service: "holiday.v1.HolidaysService", type: .unary)
        }
    }
}
